name: Create Archive
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: TheDoctor0/zip-release@0.7.1
        with:
          type: "zip"
          filename: "release.zip"
          exclusions: "*.git* /*node_modules/* .editorconfig"
      - name: Upload PreRelease
        if: contains(fromJson('["beta", "dev"]'), github.event.ref)
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release.zip"
          prerelease: True
      - name: Upload Release
        if: contains(fromJson('["beta", "dev"]'), github.event.ref) == false
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release.zip"
          generateReleaseNotes: True
          replacesArtifacts: True
